### ISSUE TITLE
mongo-mem not zero-based

### ISSUE THREAD

**Issue by mattparlane** [erh/mongo-munin#1]
Hi there...

How about this:
`
diff --git a/mongo_mem b/mongo_mem
index af484ba..dc0fa28 100755
--- a/mongo_mem
+++ b/mongo_mem
@@ -26,7 +26,7 @@ def doData():
 def doConfig():

```
 print "graph_title MongoDB memory usage"
```
-    print "graph_args --base 1000"
-    print "graph_args --base 1000 -l 0"
   print "graph_vlabel mb ${graph_period}"
   print "graph_category MongoDB"
  `

Cheers,

Matt

**Comment by mattparlane** [comment]
ugh, it's screwed up my formatting...  try this:

<pre>
diff --git a/mongo_mem b/mongo_mem
index af484ba..dc0fa28 100755
--- a/mongo_mem
+++ b/mongo_mem
@@ -26,7 +26,7 @@ def doData():
 def doConfig():
 
     print "graph_title MongoDB memory usage"
-    print "graph_args --base 1000"
+    print "graph_args --base 1000 -l 0"
     print "graph_vlabel mb ${graph_period}"
     print "graph_category MongoDB"
 </pre>

**Comment by erh** [comment]
makes sense.
if you fork and commit i can merge - otherwise i'll just copy what you did, but you won't get credit :)

**Comment by mattparlane** [comment]
not too fussed about the credit...  :)

**Comment by erh** [comment]
done
